package com.isabella.dechat.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.isabella.dechat.bean.FriendListDataBean;
import com.isabella.dechat.bean.NearbyDataBean;
import com.isabella.dechat.bean.PhotolistBean;
import com.isabella.dechat.bean.UserInfoDataBean;

import com.isabella.dechat.dao.FriendListDataBeanDao;
import com.isabella.dechat.dao.NearbyDataBeanDao;
import com.isabella.dechat.dao.PhotolistBeanDao;
import com.isabella.dechat.dao.UserInfoDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendListDataBeanDaoConfig;
    private final DaoConfig nearbyDataBeanDaoConfig;
    private final DaoConfig photolistBeanDaoConfig;
    private final DaoConfig userInfoDataBeanDaoConfig;

    private final FriendListDataBeanDao friendListDataBeanDao;
    private final NearbyDataBeanDao nearbyDataBeanDao;
    private final PhotolistBeanDao photolistBeanDao;
    private final UserInfoDataBeanDao userInfoDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendListDataBeanDaoConfig = daoConfigMap.get(FriendListDataBeanDao.class).clone();
        friendListDataBeanDaoConfig.initIdentityScope(type);

        nearbyDataBeanDaoConfig = daoConfigMap.get(NearbyDataBeanDao.class).clone();
        nearbyDataBeanDaoConfig.initIdentityScope(type);

        photolistBeanDaoConfig = daoConfigMap.get(PhotolistBeanDao.class).clone();
        photolistBeanDaoConfig.initIdentityScope(type);

        userInfoDataBeanDaoConfig = daoConfigMap.get(UserInfoDataBeanDao.class).clone();
        userInfoDataBeanDaoConfig.initIdentityScope(type);

        friendListDataBeanDao = new FriendListDataBeanDao(friendListDataBeanDaoConfig, this);
        nearbyDataBeanDao = new NearbyDataBeanDao(nearbyDataBeanDaoConfig, this);
        photolistBeanDao = new PhotolistBeanDao(photolistBeanDaoConfig, this);
        userInfoDataBeanDao = new UserInfoDataBeanDao(userInfoDataBeanDaoConfig, this);

        registerDao(FriendListDataBean.class, friendListDataBeanDao);
        registerDao(NearbyDataBean.class, nearbyDataBeanDao);
        registerDao(PhotolistBean.class, photolistBeanDao);
        registerDao(UserInfoDataBean.class, userInfoDataBeanDao);
    }
    
    public void clear() {
        friendListDataBeanDaoConfig.clearIdentityScope();
        nearbyDataBeanDaoConfig.clearIdentityScope();
        photolistBeanDaoConfig.clearIdentityScope();
        userInfoDataBeanDaoConfig.clearIdentityScope();
    }

    public FriendListDataBeanDao getFriendListDataBeanDao() {
        return friendListDataBeanDao;
    }

    public NearbyDataBeanDao getNearbyDataBeanDao() {
        return nearbyDataBeanDao;
    }

    public PhotolistBeanDao getPhotolistBeanDao() {
        return photolistBeanDao;
    }

    public UserInfoDataBeanDao getUserInfoDataBeanDao() {
        return userInfoDataBeanDao;
    }

}
